### ISSUE TITLE
Highlight Boulders

### ISSUE THREAD

**Issue by craigins** [craigins/CoreKeeperMapTool#2]
Add feature to highlight boulders / 4 square tiles of the same ore.  All boulders or filter to specific boulders

**Comment by Z3R0Gravitas** [comment]
Hey! This please! Just to highlight the boulder's pixels would probably be great. But depending on how visible that is, when zoomed out, a circle halo of some kind (around each bolder) might be handy. 😉

**Comment by craigins** [comment]
Should properly highlight boulder pixels now.
