### ISSUE TITLE
Auto-update or quick refresh button (please add! 🙂)

### ISSUE THREAD

**Issue by Z3R0Gravitas** [craigins/CoreKeeperMapTool#7]
To aid with updating the map more quickly when searching along distance arcs. 🙂

Ideally re-centres map on same spot, where it was zoomed into.

**Comment by MzHub** [comment]
There are two main ways to go with this:

- for browsers, the new Filesystem Access API is required.
- or the maptool could be ported into, for example, Electron desktop app.

There are downsides to both.

Filesystem Access API only works in Chrome and Edge, as other browser vendors deem it a security and privacy risk currently. It would have to be made into an optional feature, and fall back to the old file input.

With a desktop app the downside is having to download and somehow update the application.

------

Aside from allowing reloading and watching files for changes, the Filesystem Access API also allows to "open folder", which could be used to make it easier for users to browse their saved maps.

**Comment by craigins** [comment]
Mz added some updates to keep the pan/zoom.  I just finished implementing the file api and it appears to work!  enjoy.
